// Generates a TypeScript module exporting all Italian municipality tokens.
// Source: matteocontrini/comuni-json (ISTAT-based, ~7900 comuni).
// Run: node scripts/generate-comuni.mjs
//
// Output: src/lib/italian-comuni.ts (a Set<string> of normalized lowercase tokens
// extracted from comune names, used by company-lookup route to distinguish
// geographic tokens from name tokens in user queries).

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const repoRoot = path.resolve(__dirname, '..')

const SOURCE_URL = 'https://raw.githubusercontent.com/matteocontrini/comuni-json/master/comuni.json'
const OUTPUT_PATH = path.join(repoRoot, 'src', 'lib', 'italian-comuni.ts')

console.log('Fetching comuni list from:', SOURCE_URL)
const res = await fetch(SOURCE_URL)
if (!res.ok) {
  console.error('Failed to fetch:', res.status, res.statusText)
  process.exit(1)
}
const data = await res.json()
console.log(`Loaded ${data.length} comuni.`)

// Tokens that are too generic to act as city markers (would over-trigger geo classification).
// These appear as fragments in many comune names and must NOT be treated as cities by themselves.
const GENERIC_BLOCKLIST = new Set([
  'san','santa','santo','santi','sant','sotto','sopra','alta','alto','bassa','basso',
  'nuova','nuovo','vecchia','vecchio','grande','piccolo','piccola','del','della','delle',
  'dei','degli','con','sul','sulla','sui','nel','nella','dal','dalla','val','valle','via',
  'isola','monte','colle','torre','villa','borgo','castel','castello','ponte','porto',
  'rocca','terra','terre','lago','mare','fiume','piano','piana','prato','campo','foresta',
  'casa','case','dei','reggio','emilia',
])

const tokens = new Set()

for (const c of data) {
  if (!c?.nome) continue
  const normalized = String(c.nome)
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // diacritics
    .replace(/['`\u2019\u02bc]/g, ' ') // any apostrophe variant → space
    .replace(/[^a-z0-9\s\-/]/g, ' ')

  // Split by whitespace, dash, slash
  const parts = normalized.split(/[\s\-/]+/).filter(t => t && t.length >= 3)

  // Add the full collapsed name (no spaces) AND each token
  const fullCollapsed = parts.join('')
  if (fullCollapsed.length >= 4) tokens.add(fullCollapsed)

  for (const p of parts) {
    if (GENERIC_BLOCKLIST.has(p)) continue
    tokens.add(p)
  }
}

// Always include the major province/region anchors (covers province codes and regional names)
const ANCHORS = [
  'milano','roma','napoli','torino','bologna','firenze','genova','palermo','bari','catania',
  'venezia','verona','padova','brescia','bergamo','modena','parma','treviso','trieste','vicenza',
  'cagliari','messina','livorno','perugia','reggio','ravenna','rimini','salerno','foggia','ferrara',
  'latina','monza','pescara','trento','bolzano','siracusa','taranto','novara','cremona','como',
  'pavia','mantova','lecco','varese','lodi','ancona','matera','cosenza','catanzaro','aosta',
  'lecce','terni','viterbo','savona','imperia','alessandria','asti','cuneo','biella','vercelli',
  'udine','pordenone','gorizia','sondrio','olbia','sassari','potenza','crotone','avellino',
  'benevento','caserta','agrigento','enna','ragusa','trapani','frosinone','rieti','grosseto',
  'siena','arezzo','pistoia','lucca','massa','carrara','piacenza','spezia','brindisi',
  'campobasso','isernia','nuoro','oristano','urbino','pesaro','fermo','macerata','teramo',
  'chieti','aquila','milanese','brianza','veneto','lombardia','piemonte','toscana','sicilia',
  'sardegna','calabria','puglia','campania','lazio','marche','umbria','abruzzo','molise',
  'liguria','basilicata','emilia','romagna','friuli','giulia','valle','aosta',
]
for (const a of ANCHORS) tokens.add(a)

const sorted = [...tokens].sort()

const ts = `// Auto-generated by scripts/generate-comuni.mjs — DO NOT EDIT MANUALLY.
// Source: matteocontrini/comuni-json (ISTAT-based, ${data.length} comuni)
// Generated: ${new Date().toISOString()}
//
// Contains ${sorted.length} normalized tokens extracted from all Italian municipality names,
// plus regional/provincial anchors. Used by company-lookup to classify query tokens as
// geographic (city/region/province) vs name (company name) for the FINAL GATE anti-omonym
// validation and for fatturatoitalia.it slug matching.
//
// Tokens are lowercase, diacritic-free, and stripped of generic markers (san, santa, monte,
// villa, etc.) which would otherwise over-trigger geo classification on queries.

export const ITALIAN_COMUNI_TOKENS: ReadonlySet<string> = new Set([
${sorted.map(t => `  '${t.replace(/'/g, "\\'")}'`).join(',\n')}
])
`

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
fs.writeFileSync(OUTPUT_PATH, ts, 'utf8')

console.log(`Wrote ${sorted.length} tokens to ${OUTPUT_PATH}`)
console.log('Sample:', sorted.slice(0, 10).join(', '), '...')
console.log('Includes carate?', tokens.has('carate'))
console.log('Includes sovico?', tokens.has('sovico'))
console.log('Includes vimercate?', tokens.has('vimercate'))
console.log('Includes marsala?', tokens.has('marsala'))
console.log('Includes catanzaro?', tokens.has('catanzaro'))
